In [10]:
import numpy as np
import cv2
%run ../Boxes/ORB_box.ipynb
%run ../Boxes/HOG_box.ipynb

In [11]:
# Read the image 
image = cv2.imread('E:/2nd term 3rd year/Neural Network/Project/men/'+str(2)+'/'+str(2)+'_men ('+str(5)+').JPG', cv2.IMREAD_UNCHANGED)

# Convert the color channels from BGR to RGB
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

Feature_vector = HOG_box(image)

print(Feature_vector)

[0.19748858 0.10310785 0.08663886 ... 0.11992455 0.14227502 0.2891347 ]


In [12]:
image = cv2.imread('E:/2nd term 3rd year/Neural Network/Project/men/'+str(2)+'/'+str(2)+'_men ('+str(5)+').JPG', cv2.IMREAD_UNCHANGED)
des=ORB_box(image,1000)
print(des)

[[ 49  32  80 ...   0  98 128]
 [ 33  32  22 ...   8  18   0]
 [ 96  32  18 ...   8   2   2]
 ...
 [ 66  32  18 ...   0   3   4]
 [193 112 145 ...  48  66  48]
 [  0  32  17 ...   0   6  48]]
