In [5]:
import numpy as np
import cv2
%run ../Boxes/ORB_box.ipynb
%run ../Boxes/HOG_box.ipynb
%run ../Boxes/LBP_box.ipynb

In [2]:
# Read the image 
image = cv2.imread('E:/2nd term 3rd year/Neural Network/Project/men/'+str(0)+'/'+str(0)+'_men ('+str(1)+').JPG', cv2.IMREAD_UNCHANGED)
Feature_vector = HOG_box(image)
# with open('testzero.csv', 'w') as f:
#     f.truncate(0)
# with open('testzero.csv', 'a') as f:
#         # Save in csv file
#         np.savetxt('testzero.csv',  Feature_vector, delimiter=',')
print(len(Feature_vector))

4356


In [3]:
print(len(Feature_vector))

4356


In [4]:
image = cv2.imread('E:/2nd term 3rd year/Neural Network/Project/men/'+str(2)+'/'+str(2)+'_men ('+str(5)+').JPG', cv2.IMREAD_UNCHANGED)
des=ORB_box(image,1000)
print(des)
print(len(des))

[[231  55 234 ... 116 251 215]
 [ 88  60 159 ... 224   7  58]
 [ 63  12 147 ... 247 106 164]
 ...
 [122 172  16 ...  76 142  14]
 [ 32 150 113 ... 203 198 253]
 [149 183  35 ... 142 222 212]]
1000


In [6]:
image = cv2.imread('E:/2nd term 3rd year/Neural Network/Project/men/'+str(2)+'/'+str(2)+'_men ('+str(5)+').JPG', cv2.IMREAD_UNCHANGED)
Feature_vector = HOG_box(image)
print(len(Feature_vector))
Feature_vector= np.concatenate((Feature_vector,LBP_box(image)))
print(len(Feature_vector))

4356
4614
